scenario:
  net_file: "networks/BIGNET.net.xml"
  map_prefix: "bignet"
  entry_edges:
    - "-E29"
    - "-E33"
    - "-E32"
    - "-E30"
    - "-E34"
    - "-E31"
    - "-E35"
    - "-E36"
    - "-E37"
    - "-E40"
    - "-E39"
    - "-E38"
  exit_edges:
    - "E29"
    - "E33"
    - "E32"
    - "E30"
    - "E34"
    - "E31"
    - "E35"
    - "E36"
    - "E37"
    - "E40"
    - "E39"
    - "E38"
  turn_mapping:
    "-E29":
      S: ["E30", "E34", "E31"]
      L: ["E35", "E36", "E37"]
      R: ["E40", "E39", "E38"]
    "-E33":
      S: ["E30", "E34", "E31"]
      L: ["E35", "E36", "E37"]
      R: ["E40", "E39", "E38"]
    "-E32":
      S: ["E30", "E34", "E31"]
      L: ["E35", "E36", "E37"]
      R: ["E40", "E39", "E38"]
    "-E30":
      S: ["E29", "E33", "E32"]
      L: ["E40", "E39", "E38"]
      R: ["E35", "E36", "E37"]
    "-E34":
      S: ["E29", "E33", "E32"]
      L: ["E40", "E39", "E38"]
      R: ["E35", "E36", "E37"]
    "-E31":
      S: ["E29", "E33", "E32"]
      L: ["E40", "E39", "E38"]
      R: ["E35", "E36", "E37"]
    "-E35":
      S: ["E40", "E39", "E38"]
      L: ["E30", "E34", "E31"]
      R: ["E29", "E33", "E32"]
    "-E36":
      S: ["E40", "E39", "E38"]
      L: ["E30", "E34", "E31"]
      R: ["E29", "E33", "E32"]
    "-E37":
      S: ["E40", "E39", "E38"]
      L: ["E30", "E34", "E31"]
      R: ["E29", "E33", "E32"]
    "-E40":
      S: ["E35", "E36", "E37"]
      L: ["E29", "E33", "E32"]
      R: ["E30", "E34", "E31"]
    "-E39":
      S: ["E35", "E36", "E37"]
      L: ["E29", "E33", "E32"]
      R: ["E30", "E34", "E31"]
    "-E38":
      S: ["E35", "E36", "E37"]
      L: ["E29", "E33", "E32"]
      R: ["E30", "E34", "E31"]
  pcu_weights:
    motorcycle: 0.25
    passenger: 1.0
    bus: 3.0
    other: 1.0
  demand:
    total_pcu_per_hour:
      low: 5000
      med: 10000
      high: 15000
    entry_dirichlet_alpha: 2.0
  vehicle_mix_mean:
    motorcycle: 0.84
    passenger: 0.12
    bus: 0.03
    other: 0.01
  vehicle_mix_kappa: 50
  turning:
    mean_LSR: [0.15, 0.70, 0.15]
    kappa: 30